---
- name: Ensure dependencies are install
  apt: 
    name: "{{ item }}"
    update_cache: yes
    state: present
  loop:
    - apt-transport-https 
    - ca-certificates
    - curl
    - gnupg 
    - lsb-release
    - software-properties-common

- name: Check if Docker is already installed
  package_facts:
    manager: "auto"

- name: Docker check result
  debug: 
    msg: "Dcoker is already installed"
  when: "'docker-ce' in ansible_facts.packages"

- name: Install Docker
  block:   
    - name: Add the GPG key from the official Docker repository in our system
      shell: curl -fsSL {{ docker_url }}/gpg | sudo apt-key add -
      args:
        warn: false
      when: docker_url is defined

    - name: Add the Docker repository to the APT sources
      apt_repository:
        repo: "{{ docker_apt_repository }}"
        state: present
        update_cache: true
      when: docker_apt_repository is defined
    - name: Install Docker package
      apt:
        name: docker-ce
        state: latest

    - name: Add docker permissions
      shell: sudo usermod -aG docker ${USER}
  when: "'docker-ce' not in ansible_facts.packages"

- name: Ensure Docker service is running
  service:
    name: "docker"
    state: started
