---
# tasks file for deploy-webapp

- name: "DEPLOY WEBAPP - Install Docker"
  import_task: docker_{{ ansible_os_family }}.yml
  tags: 
    - docker
    - deploy-webapp

- name: "DEPLOY WEBAPP - Lauch Webapp deployment"
  import_task: deploy_webapp.yml
  tags: 
    - deploy-webapp