---
- name: "DEPLOY WEBAPP - Install Docker"
  include_tasks:
    file: docker_debian.yml
    apply:
      tags:
        - docker
  when: ansible_distribution == "Debian"

- name: "DEPLOY WEBAPP - Lauch Webapp deployment"
  include_tasks:
    file: deploy_webapp.yml
    apply:
      tags:
        - webapp
  tags: 
    - always

...